name: run main.py

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # run at 9:00 (UTC+8)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner


          
      - name: execute py script # run main.py
        run: |
          mkdir test
          git config --local user.name actions-user

          git config --local user.email "actions@github.com" 
          
          git fetch

          git add *

          git commit -am "GH Action   Files added    $(date)" 
 
          git push -f origin main
